### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devrimgunduz** [gabfl/bigquery_fdw#16]
Hi,

I started packaging bigquery_fdw for the PostgreSQL RPM repository. Looks like there are a lot of commits since the last release. Want to release a new version so that I can keep the package up to date?

We don't pull from git, we use the tarballs to build the package.

Regards, Devrim

**Comment by gabfl** [comment]
@devrimgunduz do you mean a version of bigquery_fdw for PostgreSQL 12?

**Comment by devrimgunduz** [comment]
...or that? I thought it is already v12 compatible, no?

**Comment by gabfl** [comment]
I will make sure it does and push a new release. Will try to do it by the end of the week

**Comment by gabfl** [comment]
@devrimgunduz I pushed version 1.6 (see https://pypi.org/project/bigquery-fdw/1.6/
) with the latest commits, verified compatibility for Postgres 12 and updated BigQuery SDKs

Let me know if you need anything else

**Comment by devrimgunduz** [comment]
Hi @gabfl ,

Thanks a lot. Can you also please release the tarball in here, so that I can RPMify it?

Regards, Devrim

**Comment by gabfl** [comment]
Sure, what do you need exactly? I simple tarball of the project at the base of the repo? Gzipped? Any specific naming convention?

**Comment by devrimgunduz** [comment]
Hi,

You can follow the same procedure that you already did here. A tarball from master branch will be awesome.

https://github.com/gabfl/bigquery_fdw/releases

**Comment by gabfl** [comment]
I did not realize you wanted a Github release. In recent times I have been only pushing them to Pypi.

I just published a new GH release.

**Comment by devrimgunduz** [comment]
All good @gabfl . Thanks a lot!
