### ISSUE TITLE
Use pgsql-io/mulitcorn2 as the basis to support pg13 & pg14

### ISSUE THREAD

**Issue by luss** [gabfl/bigquery_fdw#25]
Will you consider to change your doc?

**Comment by luss** [comment]
oops, thats https://github.com/pgsql-io/multicorn2

**Comment by gabfl** [comment]
excuse me?

**Comment by luss** [comment]
The multicorn2 project supports python3 with pg10 thru pg14.  One of the
projects used to verify this is BigQuery FDW.

**Comment by gabfl** [comment]
@luss 

Hi Denis, apologies for taking so long to circle back on this. I am currently making a pull request to replace the current fork with your version alongside other minor changes.

Thank you for taking the time to build a fork of Multicorn that helps https://github.com/gabfl/bigquery_fdw stay relevant with newer versions of PostgreSQL

**Comment by gabfl** [comment]
resolved!

**Comment by luss** [comment]
Excellent.  The open challenges for Multicorn2 on pg14 likely don't affect
BigQuery.  They have to do with Join Pushdown on Updates afaik.

--Luss

**Comment by gabfl** [comment]
Indeed everything I tested seemed to work perfectly with PG 14

**Comment by luss** [comment]
Kewl.  Glad to hear it.
